.PHONY: help db-up db-down migrate revision test lint fmt ingest extract resolve project eval api install

PG_VER ?= 16

help:
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN{FS=":.*?## "}{printf "\033[36m%-14s\033[0m %s\n", $$1, $$2}'

install: ## Sync all dependency groups via uv
	uv sync --extra dev --extra pipeline --extra api

db-up: ## Start the local Postgres 16 cluster (native apt install)
	sudo pg_ctlcluster $(PG_VER) main start || true

db-down: ## Stop the local Postgres 16 cluster (native apt install)
	sudo pg_ctlcluster $(PG_VER) main stop || true

db-up-docker: ## Start Postgres + pgvector via docker compose (alternative)
	docker compose up -d

db-down-docker: ## Stop the docker compose Postgres
	docker compose down

migrate: ## Apply database migrations
	uv run alembic upgrade head

revision: ## Create a new autogenerated migration (m="msg")
	uv run alembic revision --autogenerate -m "$(m)"

test: ## Run the test suite
	uv run pytest

lint: ## Lint with ruff
	uv run ruff check src tests

fmt: ## Auto-format + fix with ruff
	uv run ruff check --fix src tests && uv run ruff format src tests

ingest: ## Ingest 13D/13G filings (n=100)
	uv run clew ingest edgar --form 13D --limit $(or $(n),100)

extract: ## Run extraction over ingested documents
	uv run clew extract run

resolve: ## Run entity resolution
	uv run clew resolve run

project: ## Rebuild graph + vector projections from the ledger
	uv run clew project all

eval: ## Run the evaluation harness
	uv run clew eval all

api: ## Serve the read-only API
	uv run uvicorn clew.api.main:app --reload --port 8000
